### ISSUE TITLE
count(): Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by bayareawebpro** [andriell/php-osm-to-sql#2]
I'm working off the example from the direct database import running it within a console command.

![Screen Shot 2019-04-05 at 12 03 19 AM](https://user-images.githubusercontent.com/2476179/55609714-3e80f500-5736-11e9-96b1-38d8cc49df6f.png)

**Comment by andriell** [comment]
This has been fixed in v2.0.9
